// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    return {
      grid: {
        width: 24,
        height: 16,
        tile: {
          width: 16,
          height: 16
        }
      }
    };
  });

}).call(this);
