// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty'], function(crafty) {
    return crafty.c('Wall', {
      init: function() {
        this.requires('2D, Canvas, Image, Tile');
        return this.image('../assets/Stone Block.png');
      }
    });
  });

}).call(this);
