// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'tile', 'wall', 'settings', 'rot', 'floor', 'player'], function(crafty, tile, wall, settings, ROT) {
    return {
      width: function() {
        return settings.grid.width * settings.grid.tile.width;
      },
      height: function() {
        return (settings.grid.height * settings.grid.tile.height) + settings.grid.tile.topPadding + settings.grid.tile.bottomPadding;
      },
      make_tile: function(x, y, isWall) {
        if (isWall) {
          return crafty.e('Wall').at(x, y);
        } else {
          return crafty.e('Floor').at(x, y);
        }
      },
      digger: new ROT.Map.Uniform(settings.grid.width, settings.grid.height),
      start: function() {
        var pc;
        console.log("Width:", this.width());
        crafty.init(this.width(), this.height());
        crafty.background('rgb(80, 80, 80)');
        this.digger.create(this.make_tile);
        pc = crafty.e('Player').at(1, 1);
        crafty.viewport.init(800, 600);
        crafty.viewport.follow(pc, 0, 0);
        return null;
      }
    };
  });

}).call(this);
