// Generated by CoffeeScript 1.5.0

define(['crafty'], function(crafty) {
  return {
    start: function() {
      crafty.init(1024, 768);
      return crafty.background('rgb(60, 60, 60)');
    }
  };
});
