// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'tile', 'wall', 'settings', 'rot', 'floor', 'player'], function(crafty, tile, wall, settings, ROT) {
    return {
      width: function() {
        return settings.grid.width * settings.grid.tile.width;
      },
      height: function() {
        return (settings.grid.height * settings.grid.tile.height) + settings.grid.tile.topPadding + settings.grid.tile.bottomPaddi;
      },
      playerStart: null,
      make_tile: function(x, y, isWall) {
        if (isWall) {
          crafty.e('Wall').at(x, y);
        } else {
          crafty.e('Floor').at(x, y);
        }
        if (!isWall && !this.playerStart) {
          return this.playerStart = {
            x: x,
            y: y
          };
        }
      },
      digger: new ROT.Map.Uniform(settings.grid.width, settings.grid.height),
      start: function() {
        console.log("Width:", this.width());
        crafty.init(this.width(), this.height());
        crafty.background('rgb(80, 80, 80)');
        this.digger.create(this.make_tile.bind(this));
        crafty.e('Player').at(this.playerStart.x, this.playerStart.y);
        crafty.viewport.init(800, 600);
        return null;
      }
    };
  });

}).call(this);
