// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'settings'], function(crafty) {
    return crafty.c('Player', {
      init: function() {
        this.requires('2D, Canvas, Image,Tile,Fourway,Collision').fourway(10).stopOnSolids();
        this.image('assets/Character Boy.png');
        return this.bind('Moved', function() {
          console.log('Moving:', this.x, this.y);
          crafty.viewport.x = 400 - this.x;
          return crafty.viewport.y = 300 - this.y;
        });
      },
      stopOnSolids: function() {
        this.onHit('Solid', this.stopMoving);
        return this;
      },
      stopMoving: function() {
        return console.log('stopped');
      }
    });
  });

}).call(this);
