// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'settings'], function(crafty) {
    return crafty.c('Player', {
      init: function() {
        this.requires('2D, Canvas, Image,Tile,Fourway,Collision').fourway(10).collision([25, 49], [25, 91], [76, 91], [76, 49]).stopOnSolids();
        this.image('assets/Character Boy.png');
        return this.bind('Moved', function() {
          crafty.viewport.x = 400 - this.x;
          crafty.viewport.y = 300 - this.y;
          return this.z = this.y + 83;
        });
      },
      stopOnSolids: function() {
        this.onHit('Solid', this.stopMoving);
        return this;
      },
      stopMoving: function() {
        console.log('stopped');
        this._speed = 0;
        if (this._movement) {
          this.x -= this._movement.x;
          return this.y -= this._movement.y;
        }
      }
    });
  });

}).call(this);
