// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'settings'], function(crafty) {
    return crafty.c('Player', {
      init: function() {
        this.requires('2D, Canvas, Image,Tile,Fourway').fourway(10);
        return this.image('assets/Character Boy.png');
      }
    });
  });

}).call(this);
