// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    return {
      grid: {
        width: 40,
        height: 40,
        tile: {
          width: 101,
          height: 81,
          topPadding: 49,
          bottomPadding: 41
        }
      }
    };
  });

}).call(this);
