// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty', 'settings'], function(crafty, settings) {
    return crafty.c('Tile', {
      init: function() {
        console.log('init tile');
        return this.attr({
          w: settings.grid.tile.width,
          h: settings.grid.tile.height
        });
      },
      at: function(x, y) {
        this.attr({
          x: x * settings.grid.tile.width,
          y: y * settings.grid.tile.height,
          z: y * settings.grid.tile.height
        });
        return this;
      }
    });
  });

}).call(this);
