// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty'], function(crafty) {
    return crafty.c('Wall', {
      init: function() {
        this.requires('2D, Canvas, Color, Tile');
        return this.color('rgb(128,0,0)');
      }
    });
  });

}).call(this);
