// Generated by CoffeeScript 1.6.1
(function() {

  define(['crafty'], function(crafty) {
    return crafty.c('Wall', {
      init: function() {
        this.requires('2D, Canvas, Image, Tile, Solid, Collision').collision([0, 0], [0, 81], [101, 81], [101, 0]);
        return this.image('assets/Stone Block Tall.png');
      }
    });
  });

}).call(this);
